export const availableSkills = [
  // 언어
  "JavaScript", "TypeScript", "Java", "Kotlin", "C", "C++", "C#", "Python", "Go", "Rust", "Swift", "PHP", "Ruby",
  // 프론트엔드
  "React", "Next.js", "Vue.js", "Nuxt.js", "Angular", "Svelte", "HTML", "CSS", "SCSS", "Tailwind CSS", "Styled Components",
  // 백엔드/프레임워크
  "Spring Boot", "Spring", "Django", "Flask", "Express.js", "FastAPI", "Node.js", "NestJS", "ASP.NET Core", "Laravel",
  // 데이터베이스
  "MySQL", "PostgreSQL", "MongoDB", "SQLite", "Oracle", "MariaDB",
  // DevOps/클라우드
  "Docker", "Kubernetes", "AWS", "GCP", "Azure", "Firebase", "Vercel", "Netlify", "Heroku", "Jenkins", "GitHub Actions",
  // 협업/디자인
  "Git", "GitHub", "GitLab", "Figma", "Zeplin", "Jira", "Notion", "Slack", "UI/UX",
];

export const SKILL_DISPLAY_MAP: Record<string, string> = {
  "ai/ml": "AI/ML",
  "angular": "Angular",
  "asp.net core": "ASP.NET Core",
  "aws": "AWS",
  "c": "C",
  "c#": "C#",
  "c++": "C++",
  "css": "CSS",
  "django": "Django",
  "docker": "Docker",
  "express.js": "Express.js",
  "fastapi": "FastAPI",
  "figma": "Figma",
  "firebase": "Firebase",
  "flask": "Flask",
  "git": "Git",
  "github": "GitHub",
  "github actions": "GitHub Actions",
  "gitlab": "GitLab",
  "go": "Go",
  "gcp": "GCP",
  "graphql": "GraphQL",
  "heroku": "Heroku",
  "html": "HTML",
  "java": "Java",
  "jenkins": "Jenkins",
  "jira": "Jira",
  "kotlin": "Kotlin",
  "kubernetes": "Kubernetes",
  "laravel": "Laravel",
  "mariadb": "MariaDB",
  "mongodb": "MongoDB",
  "mysql": "MySQL",
  "nestjs": "NestJS",
  "netlify": "Netlify",
  "next.js": "Next.js",
  "notion": "Notion",
  "nuxt.js": "Nuxt.js",
  "oracle": "Oracle",
  "php": "PHP",
  "postgresql": "PostgreSQL",
  "python": "Python",
  "react": "React",
  "react native": "React Native",
  "redis": "Redis",
  "ruby": "Ruby",
  "rust": "Rust",
  "scss": "SCSS",
  "sketch": "Sketch",
  "slack": "Slack",
  "solidity": "Solidity",
  "spring": "Spring",
  "spring boot": "Spring Boot",
  "sqlite": "SQLite",
  "svelte": "Svelte",
  "swift": "Swift",
  "styled components": "Styled Components",
  "tailwind css": "Tailwind CSS",
  "typescript": "TypeScript",
  "ui/ux": "UI/UX",
  "vercel": "Vercel",
  "vue": "Vue.js",
  "vue.js": "Vue.js",
  "web3.js": "Web3.js",
  "zeplin": "Zeplin",
};
